version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secureportal
      - POSTGRES_USER=secureportal
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DB_NAME=secureportal
      - DB_USER=secureportal
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/html/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend

  tor:
    image: dperson/torproxy
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - tor_data:/var/lib/tor
    depends_on:
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  tor_data: